### ISSUE TITLE
GitLab CI integration

### ISSUE THREAD

**Issue by jokeyrhyme** [jokeyrhyme/node-init.js#75]
-   just be aware of this issue: https://github.com/flowtype/flow-bin/issues/58

**Comment by jokeyrhyme** [comment]
This works:

```yaml
before_script:
  - apt-get update -qq
  - apt-get install -qy libelf1
  - npm install

test:
  image: node:4.3
  script:
    - npm test
```

I tried a few ways of testing against multiple versions of Node.js, but they fell apart as soon as any service containers were involved. I'd suggest just testing against the single oldest supported Node.js version for now.
